# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a dataset which contains information on World Cup matches. Let's use the Pandas commands learned in the previous lesson to learn more about our data!

## Objectives
You will be able to: 
- Use pandas methods and attributes to access information about a dataset 
- Index pandas dataframes with .loc, .iloc, and column names 
- Use a boolean mask to index pandas series and dataframes

## Load the data

Load the file `'WorldCupMatches.csv'` as a DataFrame in Pandas.

In [162]:
# Import pandas using the standard alias
import pandas as pd

# Import 'WorldCupMatches.csv' as a DataFrame
df = pd.read_csv('WorldCupMatches.csv')

## Common methods and attributes

Use the correct method to look at the first 7 rows of the dataset.

In [44]:
# Print the first 7 rows of df
df.head(100)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1954,27 Jun 1954 - 17:00,Quarter-finals,Charmilles,Geneva,Germany FR,2,0,Yugoslavia,,17000.0,1,0,ZSOLT Istvan (HUN),FRANKEN Laurent (BEL),BUCHMUELLER Fritz (SUI),212,1285,FRG,YUG
96,1954,27 Jun 1954 - 17:00,Quarter-finals,Wankdorf Stadium,Berne,Hungary,4,2,Brazil,,40000.0,2,1,ELLIS Arthur (ENG),LING William (ENG),WYSSLING Paul (SUI),212,1248,HUN,BRA
97,1954,30 Jun 1954 - 18:00,Semi-finals,St. Jakob,Basel,Germany FR,6,1,Austria,,58000.0,1,0,ORLANDINI Vincenzo (ITA),ELLIS Arthur (ENG),BUCHMUELLER Fritz (SUI),462,1233,FRG,AUT
98,1954,30 Jun 1954 - 18:00,Semi-finals,La Pontaise,Lausanne,Hungary,4,2,Uruguay,Hungary win after extra time,45000.0,0,0,GRIFFITHS Benjamin (WAL),FAULTLESS Charlie (SCO),VINCENTI Raymond (FRA),462,1295,HUN,URU
99,1954,03 Jul 1954 - 17:00,Match for third place,Hardturm,Zurich,Austria,3,1,Uruguay,,32000.0,1,1,WYSSLING Paul (SUI),ZSOLT Istvan (HUN),ELLIS Arthur (ENG),3485,1239,AUT,URU

Look at the last 3 rows of the data set.

In [4]:
# Print the last 3 rows of df
df.tail(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

Get a concise summary of the data using `.info()`.

In [5]:
# Print a concise summary of df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
Year                    852 non-null int64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null int64
Away Team Goals         852 non-null int64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null int64
Half-time Away Goals    852 non-null int64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null int64
MatchID                 852 non-null int64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

Obtain a tuple representing the number of rows and number of columns

In [7]:
# Print the number of rows and columns in df
df.shape

(852, 20)

Use the appropriate attribute to get the column names

In [18]:
# Print the column names of df
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting DataFrame information

When looking at the DataFrame's `.head()`, you might have noticed that the games are structured chronologically in the DataFrame.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [19]:
# Print rows 3 through 5
df.iloc[3:6]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX

Now, print all the info from game 5-9, but we're only interested in printing out the, "Home Team Name" and the, "Away Team Name."

In [26]:
# Print rows 5 through 9 and columns 'Home Team Name' and 'Away Team Name'
df.loc[5:10,['Home Team Name','Away Team Name']]

   Home Team Name Away Team Name
5           Chile         Mexico
6      Yugoslavia        Bolivia
7             USA       Paraguay
8         Uruguay           Peru
9           Chile         France
10      Argentina         Mexico

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [40]:
# Print all info for games played in 1950 for Group 3
df.loc[df['Stage']=='Group 3']

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
8,1930,18 Jul 1930 - 14:30,Group 3,Estadio Centenario,Montevideo,Uruguay,1,0,Peru,,57735.0,0,0,LANGENUS Jean (BEL),BALWAY Thomas (FRA),CRISTOPHE Henry (BEL),201,1099,URU,PER
13,1930,21 Jul 1930 - 14:50,Group 3,Estadio Centenario,Montevideo,Uruguay,4,0,Romania,,70022.0,4,0,REGO Gilberto (BRA),WARNKEN Alberto (CHI),SAUCEDO Ulises (BOL),201,1100,URU,ROU
56,1950,25 Jun 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Sweden,3,2,Italy,,36502.0,2,1,LUTZ Jean (SUI),BERANEK Alois (AUT),TEJADA Carlos (MEX),208,1219,SWE,ITA
61,1950,29 Jun 1950 - 15:30,Group 3,Durival de Brito,Curitiba,Sweden,2,2,Paraguay,,7903.0,2,1,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208,1228,SWE,PAR
65,1950,02 Jul 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Italy,2,0,Paraguay,,25811.0,1,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),208,1218,ITA,PAR
75,1954,16 Jun 1954 - 18:00,Group 3,Wankdorf Stadium,Berne,Uruguay,2,0,Czechoslovakia,,20500.0,0,0,ELLIS Arthur (ENG),LING William (ENG),SCHICKER Werner (SUI),211,1315,URU,TCH
76,1954,16 Jun 1954 - 18:00,Group 3,Hardturm,Zurich,Austria,1,0,Scotland,,25000.0,1,0,FRANKEN Laurent (BEL),VIANA Mario (BRA),GULDE Josef (SUI),211,1236,AUT,SCO
83,1954,19 Jun 1954 - 16:50,Group 3,St. Jakob,Basel,Uruguay,7,0,Scotland,,34000.0,2,0,ORLANDINI Vincenzo (ITA),WYSSLING Paul (SUI),GUIDI Denilo (SUI),211,1313,URU,SCO
84,1954,19 Jun 1954 - 17:00,Group 3,Hardturm,Zurich,Austria,5,0,Czechoslovakia,,26000.0,4,0,STEFANOVIC Vasa (YUG),DOERFLINGER Ernst (SUI),GULDE Josef (SUI),211,1238,AUT,TCH
101,1958,08 Jun 1958 - 14:00,Group 3,Rasunda Stadium,Solna,Sweden,3,0,Mexico,,34107.0,1,0,LATYCHEV Nikolaj (URS),MOWAT Jack (SCO),ERIKSSON Arne (FIN),220,1415,SWE,MEX
104,1958,08 Jun 1958 - 19:00,Group 3,Jarnvallen,Sandviken,Hungary,1,1,Wales,,15343.0,1,1,CODESAL Jose Maria (URU),LEMESIC Leo (YUG),VAN NUFFEL Lucien (BEL),220,1407,HUN,WAL
110,1958,11 Jun 1958 - 19:00,Group 3,Rasunda Stadium,Solna,Mexico,1,1,Wales,,15150.0,0,1,LEMESIC Leo (YUG),LATYCHEV Nikolaj (URS),CODESAL Jose Maria (URU),220,1418,MEX,WAL
116,1958,12 Jun 1958 - 19:00,Group 3,Rasunda Stadium,Solna,Sweden,2,1,Hungary,,38850.0,1,0,MOWAT Jack (SCO),VAN NUFFEL Lucien (BEL),DRAGVOLL Georg (NOR),220,1406,SWE,HUN
117,1958,15 Jun 1958 - 14:00,Group 3,Rasunda Stadium,Solna,Sweden,0,0,Wales,,30287.0,0,0,VAN NUFFEL Lucien (BEL),LEMESIC Leo (YUG),LATYCHEV Nikolaj (URS),220,1438,SWE,WAL
120,1958,15 Jun 1958 - 19:00,Group 3,Jarnvallen,Sandviken,Hungary,4,0,Mexico,,13300.0,1,0,ERIKSSON Arne (FIN),CODESAL Jose Maria (URU),MOWAT Jack (SCO),220,1403,HUN,MEX
127,1958,17 Jun 1958 - 19:00,Group 3,Rasunda Stadium,Solna,Wales,2,1,Hungary,,2823.0,0,1,LATYCHEV Nikolaj (URS),CODESAL Jose Maria (URU),ERIKSSON Arne (FIN),220,1408,WAL,HUN
137,1962,30 May 1962 - 15:00,Group 3,Estadio Sausalito,Vina Del Mar,Brazil,2,0,Mexico,,10484.0,0,0,DIENST Gottfried (SUI),STEINER Carl (AUT),SCHWINTE Pierre (FRA),231,1461,BRA,MEX
141,1962,31 May 1962 - 15:00,Group 3,Estadio Sausalito,Vina Del Mar,Czechoslovakia,1,0,Spain,,12700.0,0,0,STEINER Carl (AUT),MARINO Esteban (URU),VAN ROSBERG Walter Jose (CUW),231,1498,TCH,ESP
145,1962,02 Jun 1962 - 15:00,Group 3,Estadio Sausalito,Vina Del Mar,Brazil,0,0,Czechoslovakia,,14903.0,0,0,SCHWINTE Pierre (FRA),MASSARO Artur (CHI),DIENST Gottfried (SUI),231,1462,BRA,TCH
149,1962,03 Jun 1962 - 15:00,Group 3,Estadio Sausalito,Vina Del Mar,Spain,1,0,Mexico,,11875.0,0,0,TESANIC Branko (YUG),VICUNA Claudio (CHI),VAN ROSBERG Walter Jose (CUW),231,1497,ESP,MEX
153,1962,06 Jun 1962 - 15:00,Group 3,Estadio Sausalito,Vina Del Mar,Brazil,2,1,Spain,,18715.0,0,1,BUSTAMANTE Sergio (CHI),MARINO Esteban (URU),SUNDHEIM Jose Antonio (COL),231,1460,BRA,ESP
157,1962,07 Jun 1962 - 15:00,Group 3,Estadio Sausalito,Vina Del Mar,Mexico,3,1,Czechoslovakia,,10648.0,2,1,DIENST Gottfried (SUI),TESANIC Branko (YUG),SUNDHEIM Jose Antonio (COL),231,1544,MEX,TCH
170,1966,12 Jul 1966 - 19:30,Group 3,Goodison Park,Liverpool,Brazil,2,0,Bulgaria,,47308.0,1,0,TSCHENSCHER Kurt (GER),McCABE George (ENG),TAYLOR John (ENG),238,1596,BRA,BUL
173,1966,13 Jul 1966 - 19:30,Group 3,Old Trafford Stadium,Manchester,Portugal,3,1,Hungary,,29886.0,1,0,CALLAGHAN Leo (WAL),HOWLEY Kevin (ENG),CLEMENTS William (ENG),238,1675,POR,HUN
178,1966,15 Jul 1966 - 19:30,Group 3,Goodison Park,Liverpool,Hungary,3,1,Brazil,,51387.0,1,1,DAGNALL Kenneth (ENG),HOWLEY Kevin (ENG),YAMASAKI MALDONADO Arturo (MEX),238,1597,HUN,BRA
180,1966,16 Jul 1966 - 15:00,Group 3,Old Trafford Stadium,Manchester,Portugal,3,0,Bulgaria,,25438.0,2,0,CODESAL Jose Maria (URU),GOICOECHEA Roberto (ARG),TSCHENSCHER Kurt (GER),238,1602,POR,BUL
186,1966,19 Jul 1966 - 19:30,Group 3,Goodison Park,Liverpool,Portugal,3,1,Brazil,,58479.0,2,0,McCABE George (ENG),CALLAGHAN Leo (WAL),DAGNALL Kenneth (ENG),238,1598,POR,BRA
189,1966,20 Jul 1966 - 19:30,Group 3,Old Trafford Stadium,Manchester,Hungary,3,1,Bulgaria,,24129.0,2,1,GOICOECHEA Roberto (ARG),GARDEAZABAL Juan (ESP),CODESAL Jose Maria (URU),238,1599,HUN,BUL
203,1970,02 Jun 1970 - 16:00,Group 3,Jalisco,Guadalajara,England,1,0,Romania,,50560.0,0,0,LORAUX Vital (BEL),MACHIN Roger (FRA),DE LEO Diego (MEX),250,1812,ENG,ROU
206,1970,03 Jun 1970 - 16:00,Group 3,Jalisco,Guadalajara,Brazil,4,1,Czechoslovakia,,52897.0,1,1,BARRETO RUIZ Ramon (URU),KLEIN Abraham (ISR),YAMASAKI MALDONADO Arturo (MEX),250,1770,BRA,TCH
210,1970,06 Jun 1970 - 16:00,Group 3,Jalisco,Guadalajara,Romania,2,1,Czechoslovakia,,56818.0,0,1,DE LEO Diego (MEX),EMSBERGER Gyula (HUN),LORAUX Vital (BEL),250,1919,ROU,TCH
214,1970,07 Jun 1970 - 12:00,Group 3,Jalisco,Guadalajara,Brazil,1,0,England,,66843.0,0,0,KLEIN Abraham (ISR),YAMASAKI MALDONADO Arturo (MEX),MACHIN Roger (FRA),250,1764,BRA,ENG
218,1970,10 Jun 1970 - 16:00,Group 3,Jalisco,Guadalajara,Brazil,3,2,Romania,,50804.0,2,1,MARSCHALL Ferdinand (AUT),BARRETO RUIZ Ramon (URU),LORAUX Vital (BEL),250,1769,BRA,ROU
222,1970,11 Jun 1970 - 16:00,Group 3,Jalisco,Guadalajara,England,1,0,Czechoslovakia,,49292.0,0,0,MACHIN Roger (FRA),EMSBERGER Gyula (HUN),MARSCHALL Ferdinand (AUT),250,1813,ENG,TCH
236,1974,15 Jun 1974 - 16:00,Group 3,Niedersachsenstadion,Hanover,Uruguay,0,2,Netherlands,,55100.0,0,1,PALOTAI Karoly (HUN),KAZAKOV Pavel (URS),RAINEA Nicolae (ROU),262,2098,URU,NED
237,1974,15 Jun 1974 - 16:00,Group 3,Rheinstadion,D�Sseldorf,Sweden,0,0,Bulgaria,,23800.0,0,0,PEREZ NUNEZ Edison A. (PER),GONZALEZ ARCHUNDIA Alfonso (MEX),SUPPIAH George (SIN),262,1995,SWE,BUL
244,1974,19 Jun 1974 - 19:30,Group 3,Westfalenstadion,Dortmund,Netherlands,0,0,Sweden,,53700.0,0,0,WINSEMANN Werner (CAN),TSCHENSCHER Kurt (GER),THOMAS Clive (WAL),262,2097,NED,SWE
245,1974,19 Jun 1974 - 19:30,Group 3,Niedersachsenstadion,Hanover,Bulgaria,1,1,Uruguay,,13400.0,0,0,TAYLOR John (ENG),BABACAN Dogan (TUR),OHMSEN Klaus (GER),262,1996,BUL,URU
252,1974,23 Jun 1974 - 16:00,Group 3,Westfalenstadion,Dortmund,Bulgaria,1,4,Netherlands,,53300.0,0,2,BOSKOVIC Tony (AUS),BIWERSI Ferdinand (GER),ESCHWEILER Walter (GER),262,1990,BUL,NED
254,1974,23 Jun 1974 - 16:00,Group 3,Rheinstadion,D�Sseldorf,Sweden,3,0,Uruguay,,28300.0,0,0,LINEMAYR Erich (AUT),LLOBREGAT Vicente (VEN),ALDINGER Heinz (GER),262,2181,SWE,URU
274,1978,03 Jun 1978 - 13:45,Group 3,Estadio Jos� Mar�a Minella,Mar Del Plata,Sweden,1,1,Brazil,,32569.0,1,1,THOMAS Clive (WAL),JARGUZ Alojzy (POL),NAMDAR Jafar (IRN),278,2253,SWE,BRA
275,1978,03 Jun 1978 - 13:45,Group 3,Jose Amalfitani,Buenos Aires,Austria,2,1,Spain,,40841.0,1,1,PALOTAI Karoly (HUN),BARRETO RUIZ Ramon (URU),IVANOV Anatoly (URS),278,2216,AUT,ESP
282,1978,07 Jun 1978 - 13:45,Group 3,Estadio Jos� Mar�a Minella,Mar Del Plata,Brazil,0,0,Spain,,34771.0,0,0,GONELLA Sergio (ITA),KLEIN Abraham (ISR),ITHURRALDE Arturo Andres (ARG),278,2246,BRA,ESP
283,1978,07 Jun 1978 - 13:45,Group 3,Jose Amalfitani,Buenos Aires,Austria,1,0,Sweden,,41424.0,1,0,CORVER Charles (NED),MAKSIMOVIC Dusan (SCG),SEOUDI Hedi (TUN),278,2224,AUT,SWE
290,1978,11 Jun 1978 - 13:45,Group 3,Estadio Jos� Mar�a Minella,Mar Del Plata,Brazil,1,0,Austria,,35221.0,1,0,WURTZ Robert (FRA),BOUZO Farouk (SYR),GEBREYESUS DIFUE Tesfaye (ERI),278,2215,BRA,AUT
291,1978,11 Jun 1978 - 13:45,Group 3,Jose Amalfitani,Buenos Aires,Spain,1,0,Sweden,,42132.0,0,0,BIWERSI Ferdinand (GER),ITHURRALDE Arturo Andres (ARG),PROKOP Adolf (GDR),278,2337,ESP,SWE
308,1982,13 Jun 1982 - 20:00,Group 3,Camp Nou,Barcelona,Argentina,0,1,Belgium,,95000.0,0,0,CHRISTOV Vojtech (TCH),PALOTAI Karoly (HUN),JARGUZ Alojzy (POL),293,749,ARG,BEL
312,1982,15 Jun 1982 - 21:00,Group 3,Nuevo Estadio,Elche,Hungary,10,1,El Salvador,,23000.0,3,0,AL DOY Ebrahim (BHR),CORVER Charles (NED),LUND-SORENSEN Henning (DEN),293,896,HUN,SLV
321,1982,18 Jun 1982 - 21:00,Group 3,Jose Rico Perez,Alicante,Argentina,4,1,Hungary,,32093.0,2,0,LACARNE Belaid (ALG),VAUTROT Michel (FRA),RAINEA Nicolae (ROU),293,752,ARG,HUN
324,1982,19 Jun 1982 - 21:00,Group 3,Nuevo Estadio,Elche,Belgium,1,0,El Salvador,,15000.0,1,0,MOFFATT Malcolm (NIR),CASTRO Gaston (CHI),JARGUZ Alojzy (POL),293,774,BEL,SLV
333,1982,22 Jun 1982 - 21:00,Group 3,Nuevo Estadio,Elche,Belgium,1,1,Hungary,,37000.0,0,1,WHITE Clive (ENG),ESCHWEILER Walter (GER),LACARNE Belaid (ALG),293,779,BEL,HUN
336,1982,23 Jun 1982 - 21:00,Group 3,Jose Rico Perez,Alicante,Argentina,2,0,El Salvador,,32500.0,1,0,BARRANCOS Luis (BOL),LAMO CASTILLO Augusto (ESP),LACARNE Belaid (ALG),293,751,ARG,SLV
346,1982,29 Jun 1982 - 17:15,Group 3,Sarria,Barcelona,Italy,2,1,Argentina,,43000.0,0,0,RAINEA Nicolae (ROU),GALLER Bruno (SUI),LACARNE Belaid (ALG),294,753,ITA,ARG
350,1982,02 Jul 1982 - 17:15,Group 3,Sarria,Barcelona,Argentina,1,3,Brazil,,44000.0,0,1,RUBIO VAZQUEZ Mario (MEX),ARISTIZABAL MURCIA Gilberto (COL),CASTRO Gaston (CHI),294,750,ARG,BRA
354,1982,05 Jul 1982 - 17:15,Group 3,Sarria,Barcelona,Italy,3,2,Brazil,,44000.0,2,1,KLEIN Abraham (ISR),CHAN Thomson Tam Sun (HKG),DOTCHEV Bogdan (BUL),294,788,ITA,BRA

Let's repeat the command above, but now we only want to print out the attendance column for the Group 3 games.

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [42]:
# Print the 'Attendance' column for games played in 1950 for Group 3
df.loc[df['Stage']=='Group 3',['Attendance']]

     Attendance
3        2549.0
8       57735.0
13      70022.0
56      36502.0
61       7903.0
65      25811.0
75      20500.0
76      25000.0
83      34000.0
84      26000.0
101     34107.0
104     15343.0
110     15150.0
116     38850.0
117     30287.0
120     13300.0
127      2823.0
137     10484.0
141     12700.0
145     14903.0
149     11875.0
153     18715.0
157     10648.0
170     47308.0
173     29886.0
178     51387.0
180     25438.0
186     58479.0
189     24129.0
203     50560.0
206     52897.0
210     56818.0
214     66843.0
218     50804.0
222     49292.0
236     55100.0
237     23800.0
244     53700.0
245     13400.0
252     53300.0
254     28300.0
274     32569.0
275     40841.0
282     34771.0
283     41424.0
290     35221.0
291     42132.0
308     95000.0
312     23000.0
321     32093.0
324     15000.0
333     37000.0
336     32500.0
346     43000.0
350     44000.0
354     44000.0

Throughout the entire history of the World Cup, how many home games were played by the Netherlands?

In [59]:
# Number of home games played by the Netherlands
thing = df.loc[df['Home Team Name'] == 'Netherlands']

How many games were played by the Netherlands in total?

In [64]:
# Number of games played by the Netherlands in total
thing.shape[0]

32

Next, let's try and figure out how many games the USA played in the 2014 World Cup.

In [84]:
# Number of games the USA played in the 2014 world cup
df.loc[(df['Year'] == 2014) & ((df['Home Team Name'] == 'USA') | (df['Away Team Name'] == 'USA'))].shape[0]

5

Now, let's try to find out how many countries participated in the 1986 World Cup.

Hint 1: as a first step, create a new dataset that only contains games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [113]:
# Number of countries participated in the 1986 world cup
thing = df.loc[df['Year'] == 1986,['Home Team Name','Away Team Name']]
thing2 = thing['Home Team Name'].append(thing['Away Team Name'])
print(pd.unique(thing2))
print(thing2)

['Bulgaria' 'Canada' 'Spain' 'Soviet Union' 'Argentina' 'Morocco'
 'Algeria' 'Belgium' 'Portugal' 'Paraguay' 'Scotland' 'Uruguay' 'Italy'
 'France' 'Korea Republic' 'Hungary' 'Brazil' 'England' 'Northern Ireland'
 'Mexico' 'Poland' 'Iraq' 'Denmark' 'Germany FR']
360        Bulgaria
361          Canada
362           Spain
363    Soviet Union
364       Argentina
           ...
407         England
408      Germany FR
409         Belgium
410         Belgium
411      Germany FR
Length: 104, dtype: object

In World Cup history, how many matches had 5 goals or more in total?

In [135]:
# Number of matches that had 5 or more goals in total
#print(df.head(1))
#print(df.loc[:,'Home Team Goals'])
thing = df.loc[:,'Home Team Goals']+df.loc[:,'Away Team Goals']
print(thing)
thing.loc[thing >= 5].shape

0      5
1      3
2      3
3      4
4      1
      ..
847    0
848    8
849    0
850    3
851    1
Length: 852, dtype: int64

(147,)

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column, "Half-time Goals."

In [143]:
# Create a new column 'Half-time Goals' in df
df['Half-time Goals'] = 0

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [163]:
# Print all records containing the string 'Korea'
df.loc[df['Home Team Name'].str.contains('Korea'), 'Home Team Name']

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that, for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [165]:
df.loc[df['Home Team Name'].str.contains('Korea'), 'Home Team Initials'] = 'NSK'
df.loc[df['Away Team Name'].str.contains('Korea'), 'Away Team Initials'] = 'NSK'
df.loc[df['Home Team Name'].str.contains('Korea'), 'Home Team Name'] = 'Korea'
df.loc[df['Away Team Name'].str.contains('Korea'), 'Away Team Name'] = 'Korea'




print(df.loc[df['Home Team Name'].str.contains('Korea')])
print(df.loc[df['Away Team Name'].str.contains('Korea')])

     Year              Datetime        Stage  \
179  1966  15 Jul 1966 - 19:30       Group 4
187  1966  19 Jul 1966 - 19:30       Group 4
374  1986  05 Jun 1986 - 16:00       Group A
386  1986  10 Jun 1986 - 12:00       Group A
434  1990  17 Jun 1990 - 21:00       Group E
444  1990  21 Jun 1990 - 17:00       Group E
480  1994  23 Jun 1994 - 19:30       Group C
524  1998  13 Jun 1998 - 17:30       Group E
593  2002  04 Jun 2002 - 20:30       Group D
609  2002  10 Jun 2002 - 15:30       Group D
635  2002  18 Jun 2002 - 20:30   Round of 16
642  2002  29 Jun 2002 - 20:00   Third place
655  2006  13 Jun 2006 - 15:00       Group G
710  2010  12 Jun 2010 - 13:30       Group B
753  2010  25 Jun 2010 - 16:00       Group G
802  2014  22 Jun 2014 - 16:00       Group H
818  2014  26 Jun 2014 - 17:00       Group H

                               Stadium                                City  \
179                      Ayresome Park                      Middlesbrough
187                      Ayresome Park                      Middlesbrough
374     Estadio Ol�mpico Universitario                        Mexico City
386                         Cuauhtemoc                             Puebla
434                        Dacia Arena                              Udine
444                             Friuli                              Udine
480                    Foxboro Stadium                             Boston
524                   Stade de Gerland                               Lyon
593           Busan Asiad Main Stadium                              Busan
609            Daegu World Cup Stadium                              Daegu
635          Daejeon World Cup Stadium                            Daejeon
642            Daegu World Cup Stadium                              Daegu
655  FIFA World Cup Stadium, Frankfurt                     Frankfurt/Main
710             Port Elizabeth Stadium  Nelson Mandela Bay/Port Elizabeth
753                   Mbombela Stadium                          Nelspruit
802                  Estadio Beira-Rio                       Porto Alegre
818                 Arena de Sao Paulo                          Sao Paulo

    Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
179          Korea                1                1          Chile
187          Korea                1                0          Italy
374          Korea                1                1       Bulgaria
386          Korea                2                3          Italy
434          Korea                1                3          Spain
444          Korea                0                1        Uruguay
480          Korea                0                0        Bolivia
524          Korea                1                3         Mexico
593          Korea                2                0         Poland
609          Korea                1                1            USA
635          Korea                2                1          Italy
642          Korea                2                3         Turkey
655          Korea                2                1           Togo
710          Korea                2                0         Greece
753          Korea                0                3  C�te d'Ivoire
802          Korea                2                4        Algeria
818          Korea                0                1        Belgium

          Win conditions  Attendance  Half-time Home Goals  \
179                          13792.0                     0
187                          17829.0                     1
374                          45000.0                     0
386                          20000.0                     0
434                          32733.0                     1
444                          29039.0                     0
480                          54453.0                     0
524                          39100.0                     1
593                          48760.0                     1
609                          60778.0                     0
635  Win on Golden Goal      38588.0                     0
642                          63483.0                     1
655                          48000.0                     0
710                          31513.0                     1
753                          34763.0                     0
802                          42732.0                     0
818                          61397.0                     0

     Half-time Away Goals                         Referee  \
179                     1        KANDIL Aly Hussein (EGY)
187                     0           SCHWINTE Pierre (FRA)
374                     1   AL SHANAR Fallaj Khuzam (KSA)
386                     1               SOCHA David (USA)
434                     1  JACOME GUERRERO Elias V. (ECU)
444                     0             LANESE Tullio (ITA)
480                     0            MOTTRAM Leslie (SCO)
524                     0              BENKO Gunter (AUT)
593                     0                RUIZ Oscar (COL)
609                     1                 MEIER Urs (SUI)
635                     0              MORENO Byron (ECU)
642                     3                 MANE Saad (KUW)
655                     1               POLL Graham (ENG)
710                     0            HESTER Michael (NZL)
753                     2  Alberto UNDIANO MALLENCO (ESP)
802                     3             ROLDAN Wilmar (COL)
818                     0              Ben WILLIAMS (AUS)

                   Assistant 1              Assistant 2   RoundID    MatchID  \
179     CRAWFORD William (SCO)         FINNEY Jim (ENG)       238       1609
187           ADAIR John (NIR)        TAYLOR John (ENG)       238       1679
374            IGNA Ioan (ROU)     BUTENKO Valeri (RUS)       308        460
386        URREA Joaquin (MEX)    AL SHARIF Jamal (SYR)       308        643
434      MAGNI Pierluigi (ITA)       LOUSTAU Juan (ARG)       322        175
444  DIRAMBA Jean Fidele (GAB)        JOUINI Neji (TUN)       322        290
480          MATTHYS Luc (BEL)    EVERSTIG Mikael (SWE)       337       3065
524          FRED Lencie (VAN)    SCHNEIDER Erich (GER)      1014       8732
593         DORIRI Elise (VAN)      LINDBERG Leif (SWE)  43950100   43950014
609        BEREUTER Egon (AUT)      TOMUSANGE Ali (UGA)  43950100   43950030
635      RATTALINO Jorge (ARG)     SZEKELY Ferenc (HUN)  43950200   43950056
642         ALTRAIFI Ali (KSA)     VERGARA Hector (CAN)  43950500   43950063
655         SHARP Philip (ENG)       TURNER Glenn (ENG)  97410100   97410014
710    HINTZ Jan Hendrik (NZL)    MAKASINI Tevita (TGA)    249722  300061459
753      MARTINEZ Fermin (ESP)         YUSTE Juan (ESP)    249722  300061486
802         DIAZ Eduardo (COL)  LESCANO Christian (ECU)    255931  300186495
818        CREAM Matthew (AUS)         ANAZ Hakan (AUS)    255931  300186480

    Home Team Initials Away Team Initials
179                NSK                CHI
187                NSK                ITA
374                NSK                BUL
386                NSK                ITA
434                NSK                ESP
444                NSK                URU
480                NSK                BOL
524                NSK                MEX
593                NSK                POL
609                NSK                USA
635                NSK                ITA
642                NSK                TUR
655                NSK                TOG
710                NSK                GRE
753                NSK                CIV
802                NSK                ALG
818                NSK                BEL
     Year              Datetime           Stage  \
80   1954  17 Jun 1954 - 18:00          Group 2
88   1954  20 Jun 1954 - 17:00          Group 2
171  1966  12 Jul 1966 - 19:30          Group 4
195  1966  23 Jul 1966 - 15:00   Quarter-finals
364  1986  02 Jun 1986 - 12:00          Group A
421  1990  12 Jun 1990 - 17:00          Group E
464  1994  17 Jun 1994 - 19:30          Group C
490  1994  27 Jun 1994 - 16:00          Group C
542  1998  20 Jun 1998 - 21:00          Group E
556  1998  25 Jun 1998 - 16:00          Group E
625  2002  14 Jun 2002 - 20:30          Group D
639  2002  22 Jun 2002 - 15:30   Quarter-finals
640  2002  25 Jun 2002 - 20:30      Semi-finals
672  2006  18 Jun 2006 - 21:00          Group G
691  2006  23 Jun 2006 - 21:00          Group G
721  2010  15 Jun 2010 - 20:30          Group G
725  2010  17 Jun 2010 - 13:30          Group B
737  2010  21 Jun 2010 - 13:30          Group G
742  2010  22 Jun 2010 - 20:30          Group B
756  2010  26 Jun 2010 - 16:00      Round of 16
788  2014  17 Jun 2014 - 18:00          Group H

                             Stadium                                City  \
80                          Hardturm                             Zurich
88                        Charmilles                             Geneva
171                    Ayresome Park                      Middlesbrough
195                    Goodison Park                          Liverpool
364   Estadio Ol�mpico Universitario                        Mexico City
421           Marc Antonio Bentegodi                             Verona
464                      Cotton Bowl                             Dallas
490                      Cotton Bowl                             Dallas
542                  Stade V�lodrome                         Marseilles
556                 Parc des Princes                              Paris
625         Incheon Football Stadium                            Incheon
639        Gwangju World Cup Stadium                            Gwangju
640          Seoul World Cup Stadium                              Seoul
672                   Zentralstadion                            Leipzig
691  FIFA World Cup Stadium, Hanover                            Hanover
721               Ellis Park Stadium                       Johannesburg
725              Soccer City Stadium                       Johannesburg
737                Cape Town Stadium                          Cape Town
742                   Durban Stadium                             Durban
756           Port Elizabeth Stadium  Nelson Mandela Bay/Port Elizabeth
788                   Arena Pantanal                             Cuiaba

    Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
80         Hungary                9                0          Korea
88          Turkey                7                0          Korea
171   Soviet Union                3                0          Korea
195       Portugal                5                3          Korea
364      Argentina                3                1          Korea
421        Belgium                2                0          Korea
464          Spain                2                2          Korea
490        Germany                3                2          Korea
542    Netherlands                5                0          Korea
556        Belgium                1                1          Korea
625       Portugal                0                1          Korea
639          Spain                0                0          Korea
640        Germany                1                0          Korea
672         France                1                1          Korea
691    Switzerland                2                0          Korea
721         Brazil                2                1          Korea
725      Argentina                4                1          Korea
737       Portugal                7                0          Korea
742        Nigeria                2                2          Korea
756        Uruguay                2                1          Korea
788         Russia                1                1          Korea

                               Win conditions  Attendance  \
80                                                13000.0
88                                                 4000.0
171                                               23006.0
195                                               40248.0
364                                               60000.0
421                                               32790.0
464                                               56247.0
490                                               63998.0
542                                               55000.0
556                                               45500.0
625                                               50239.0
639  Korea Republic win on penalties (3 - 5)      42114.0
640                                               65256.0
672                                               43000.0
691                                               43000.0
721                                               54331.0
725                                               82174.0
737                                               63644.0
742                                               61874.0
756                                               30597.0
788                                               37603.0

     Half-time Home Goals  Half-time Away Goals  \
80                      4                     0
88                      4                     0
171                     2                     0
195                     2                     3
364                     2                     0
421                     0                     0
464                     0                     0
490                     3                     0
542                     2                     0
556                     1                     0
625                     0                     0
639                     0                     0
640                     0                     0
672                     1                     0
691                     1                     0
721                     0                     0
725                     2                     1
737                     1                     0
742                     1                     1
756                     1                     0
788                     0                     0

                              Referee                         Assistant 1  \
80             VINCENTI Raymond (FRA)             VON GUNTER Albert (SUI)
88               MARINO Esteban (URU)            ORLANDINI Vincenzo (ITA)
171            GARDEAZABAL Juan (ESP)            KANDIL Aly Hussein (EGY)
195          ASHKENAZI Menachem (ISR)                   GALBA Karol (TCH)
364  SANCHEZ ARMINIO Victoriano (ESP)          GONZALEZ ROA Gabriel (PAR)
421               MAURO Vincent (USA)                   SNODDY Alan (NIR)
464             MIKKELSEN Peter (DEN)  CHRISTENSEN Carl-Johan Meyer (DEN)
490                QUINIOU Joel (FRA)               IVANOV Valentin (RUS)
542              WOJCIK Ryszard (POL)               POCIEGIEL Jacek (POL)
556              REZENDE Marcio (BRA)                 PINTO Arnaldo (BRA)
625               SANCHEZ Angel (ARG)                  ALTRAIFI Ali (KSA)
639           EL GHANDOUR Gamal (EGY)                 TOMUSANGE Ali (UGA)
640                   MEIER Urs (SUI)              ARNAULT Frederic (FRA)
672            ARCHUNDIA Benito (MEX)                  RAMIREZ Jose (MEX)
691            ELIZONDO Horacio (ARG)                  GARCIA Dario (ARG)
721               KASSAI Viktor (HUN)                    EROS Gabor (HUN)
725          DE BLEECKERE Frank (BEL)                 HERMANS Peter (BEL)
737                  POZO Pablo (CHI)             BASUALTO Patricio (CHI)
742        Oleg�rio BENQUEREN�A (POR)                 CARDINAL Jose (POR)
756              Wolfgang STARK (GER)            SALVER Jan-Hendrik (GER)
788               PITANA Nestor (ARG)                MAIDANA Hernan (ARG)

                  Assistant 2   RoundID    MatchID Home Team Initials  \
80         STEINER Carl (AUT)       211       1294                HUN
88   SCHONHOLZER Ernest (SUI)       211       1304                TUR
171    DIENST Gottfried (SUI)       238       1710                URS
195     SCHWINTE Pierre (FRA)       239       1702                POR
364  DIAZ PALACIO Jesus (COL)       308        395                ARG
421     COURTNEY George (ENG)       322         57                BEL
464         PEARSON Roy (ENG)       337       3050                ESP
490  HASSAN Abdel-Magid (EGY)       337       3076                GER
542        DUPANOV Yuri (BLR)      1014       8749                NED
556   ARANGO Jorge Luis (COL)      1014       8765                BEL
625      SZEKELY Ferenc (HUN)  43950100   43950047                POR
639   RAGOONATH Michael (TRI)  43950300   43950059                ESP
640         AMLER Evzen (CZE)  43950400   43950061                GER
672      VERGARA Hector (CAN)  97410100   97410029                FRA
691       OTERO Rodolfo (ARG)  97410100   97410046                SUI
721         VAMOS Tibor (HUN)    249722  300061490                BRA
725      VROMANS Walter (BEL)    249722  300061458                ARG
737   MONDRIA Francisco (CHI)    249722  300061487                POR
742     MIRANDA Bertino (POR)    249722  300111115                NGA
756         PICKEL Mike (GER)    249717  300061504                URU
788  BELATTI Juan Pablo (ARG)    255931  300186499                RUS

    Away Team Initials
80                 NSK
88                 NSK
171                NSK
195                NSK
364                NSK
421                NSK
464                NSK
490                NSK
542                NSK
556                NSK
625                NSK
639                NSK
640                NSK
672                NSK
691                NSK
721                NSK
725                NSK
737                NSK
742                NSK
756                NSK
788                NSK

Make sure to verify your answer!

In [167]:
# Check the updated columns
#done above

## Summary

In this lab, you learned how to access data within Pandas!